import Head from 'next/head'
import Nav from '../components/Nav'
import Footer from '../components/Footer'
import Github from '../components/Github'
import Kaggle from '../components/Kaggle'
import AboutMe from '../components/AboutMe'
import KnownTechs from '../components/KnownTechs'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nicholas Hellmers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Nav />

        <Github />

        <Kaggle />

        <AboutMe />

        <KnownTechs />

        <Footer />

      </main>
    </>
  )
}
